### ISSUE TITLE
WebSocket Performance

### ISSUE THREAD

**Issue by tbutts** [pereztr5/cyboard#24]
### Investigate and Remedy WebSocket Performance

As our main event grows larger, performance is becoming a bigger concern.

There appears to be room for improvement surrounding the WebSocket handlers. A new form of caching strategy would go a long ways to help us out, in this respect. The current method _scales linearly_. 

I would love to see benchmarks backing up any work done on this. There are tools [1] to help out with this.

[1]: [thor](https://github.com/observing/thor "The WebSocket god of thunder")

**Comment by tbutts** [comment]
While working on this issue, the two benchmarking tools I've been utilizing to great effect are:
* `vegeta` [link](https://github.com/tsenart/vegeta "Vegeta") - For load testing simple HTTP routes due to it's considerable ease of use compared to the insight it provides.
* `artillery` [link](https://artillery.io/ "Artillery") - For testing WebSocket endpoints and double-checking the results of `vegeta`

I really like how dead simple `vegeta` is:
``` bash
✔ 20:50:19 cyboard (ws-perf *) $ echo "GET https://localhost:8081/team/scores/split" | vegeta attack -insecure -duration=5s -workers=10 | tee big-split.bin | vegeta report
Requests      [total, rate]            250, 50.20
Duration      [total, attack, wait]    7.347564174s, 4.97999976s, 2.367564414s
Latencies     [mean, 50, 95, 99, max]  2.257389887s, 2.587048313s, 3.340115766s, 3.592472113s, 3.746949566s
Bytes In      [total, mean]            289750, 1159.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:250
Error Set:
# [...]
# Make tweaks to the cyboard, re-launch the app
# [...]
✔ 20:51:33 cyboard (ws-perf *) $ echo "GET https://localhost:8081/team/scores/split" | vegeta attack -insecure -duration=5s -workers=10 | tee big-split-indexed.bin | vegeta report
Requests      [total, rate]            250, 50.20
Duration      [total, attack, wait]    4.999693776s, 4.979999907s, 19.693869ms
Latencies     [mean, 50, 95, 99, max]  18.168608ms, 17.556564ms, 24.185745ms, 27.262695ms, 27.867354ms
Bytes In      [total, mean]            289750, 1159.00
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  100.00%
Status Codes  [code:count]             200:250
Error Set:
```

**Comment by tbutts** [comment]
I continued working with [artillery]() to test WebSocket performance. Here is the quick-but-effective YAML config:
``` yaml
# $ artillery run scoreboard.yaml
config:
  target: "wss://localhost:8081/team/scores/live"
  phases:
    - duration: 60
      arrivalRate: 4
  ws:
    # Ignore SSL certificate errors
    # - useful in *development* with self-signed certs
    rejectUnauthorized: false
scenarios:
  - engine: "ws"
    flow:
      - think: 30
```
This connects 4 users per second to the scoreboard WebSocket endpoint. The users each sit for 30 seconds and then leave. The entire test takes 60 seconds. By default, `artillery` will try to negotiate compression.
